### ISSUE TITLE
Past streamlit script runs remain in the query scope

### ISSUE THREAD

**Issue by niloc132** [deephaven/streamlit-deephaven#9]
Using streamlit's features to change state and re-run a script, or editing script files and letting streamlit re-run, causes new variables to be created in the deephaven scope (in the `__main__.__dict__` object). Later runs do not clean out old values, resulting in a long list of variables:
![screenshot883](https://github.com/deephaven/streamlit-deephaven/assets/241630/8a172128-d21e-4e55-9d71-3b4fdd4aa80c)

In theory specifying `object_id=` would let the user keep replacing the same name with new values, but it seems to not actually force the iframes to refresh (though the new object is available in scope, confirmed by checking the http://localhost:10000/ide/ panels list).

**Comment by mofojed** [comment]
Need to make sure the main dict that we add the object_id to is the same on each streamlit re-run. Also need to clear the old objects from a previous run.
